config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  resources :comments

  resources :portfolios, except: :show do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  resources :blogs do
    get :toggle_status, on: :member
  end

  get 'about-me' => 'pages#about'
  get 'contact' => 'pages#contact'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', registration: 'account', sign_up: 'signup' }
  root 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
  extend FriendlyId

  friendly_id :title, use: :slugged

  enum status: { draft: 0, published: 1 }

  belongs_to :topic

  has_many :comments, dependent: :destroy
  has_rich_text :body

  validates :title, :body, presence: true
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  layout 'blog'
  before_action :set_blog, only: [:edit, :update, :destroy, :toggle_status]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @blogs = policy_scope(Blog).order(created_at: :desc).page(params[:page]).per(5)
    authorize @blogs
    @page[:title] = 'Blog'
  end

  def show
    @blog = policy_scope(Blog).friendly.find(params[:id])
    @comments = @blog.comments.includes(:user).order(created_at: :desc).page(params[:comment_page]).per(10)
    @comment = Comment.new

    authorize @blog

    @page[:title] = @blog.title
  end

  def new
    @blog = Blog.new
    authorize @blog
  end

  def edit
    authorize @blog
  end

  def create
    @blog = Blog.new(blog_params)
    authorize @blog

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Your post is now live.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    authorize @blog

    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    authorize @blog
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Post was removed.' }
    end
  end

  def toggle_status
    authorize @blog

    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end

    redirect_to blogs_url, notice: 'Post status has been updated.'
  end

  private
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:title, :body, :status, :topic_id)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def comments_pagination
    link_to_next_page @comments, 'More', param_name: :comment_page, remote: true
  end

  def status_button_class(status)
    ['btn btn-sm', { draft: 'btn-secondary', published: 'btn-success' }[status.to_sym]]
  end
end

app/views/blogs/_actions.html.erb
<% if policy(blog).toggle_status? || policy(blog).edit? || policy(blog).destroy? %>
  <div class="mb-4 text-right">
    <div class="btn-group">
      <% if policy(blog).toggle_status? %>
        <%= link_to blog.status.capitalize, toggle_status_blog_path(blog), class: status_button_class(blog.status) %>
      <% end %>

      <% if policy(blog).edit? %>
        <%= link_to 'Edit', edit_blog_path(blog), class: 'btn btn-primary btn-sm' %>
      <% end %>

      <% if policy(blog).destroy? %>
        <%= link_to 'Delete', blog, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h2 class="blog-post-title">
    <% if policy(blog).show? %>
      <%= link_to blog.title, blog %>
    <% else %>
      blog.title
    <% end %>
  </h2>

  <p class="blog-post-meta">Published <%= time_ago_in_words blog.created_at %> ago</p>

  <%= render '/blogs/actions', blog: blog %>

  <%= blog.body %>
</div><!-- /.blog-post -->

app/views/blogs/_comments.html.erb
<div>
  <h3>Comments</h3>

  <%= render 'comments/form', comment: comment, blog: blog %>

  <div class="mt-4" data-channel="comments" data-blog-id="<%= blog.id %>">
    <%= render @comments %>
  </div>

  <% if @comments.any? %>
    <div data-comments-pagination>
      <%= comments_pagination %>
    </div>
  <% end %>
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :topic_id %>
    <%= form.collection_select :topic_id, Topic.all, :id, :title, { include_blank: true }, class: 'form-control' %>
  </div>

  <div class="field form-check form-check-inline">
    <%= form.radio_button :status, 'draft', class: 'form-check-input' %>
    <%= form.label :status_draft, 'Draft', class: 'form-check-label' %>
  </div>

  <div class="field form-check form-check-inline">
    <%= form.radio_button :status, 'published', class: 'form-check-input' %>
    <%= form.label :status_published, 'Published', class: 'form-check-label' %>
  </div>

  <div class="field form-group mt-3">
    <%= form.label :body %>
    <%= form.rich_text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-4 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>

  <div class="p-4">
    <h4 class="font-italic">Elsewhere</h4>
    <ol class="list-unstyled">
      <li><%= link_to icon('fab', 'github'), '#', class: 'fa-2x' %></li>
      <li><%= link_to icon('fab', 'twitter'), '#', class: 'fa-2x' %></li>
      <li><%= link_to icon('fab', 'facebook'), '#', class: 'fa-2x' %></li>
    </ol>
  </div>
</aside><!-- /.blog-sidebar -->

app/views/blogs/edit.html.erb
<div class="container mt-5 mb-5">
  <div class="row">
    <main role="main" class="col-md-8">
      <div class="row align-items-center">
        <h2 class="col">Editing Blog</h2>

        <% if policy(@blog).show? %>
          <div class="col text-right">
            <%= link_to 'Show', @blog, class: 'btn btn-success' %>
          </div>
        <% end %>
      </div>

      <hr>

      <%= render 'form', blog: @blog %>

      <% if policy(@blog).index? %>
        <div class="mt-3">
          <%= link_to 'Back', blogs_path %>
        </div>
      <% end %>
    </main>

    <%= render 'sidebar' %>
  </div>
</div>

app/views/blogs/index.html.erb
<main role="main" class="container mt-5">
  <% if policy(@blogs).new? %>
    <div class="mt-5 text-right">
      <%= link_to 'New Blog', new_blog_path, class: 'btn btn-success' %>
      <hr>
    </div>
  <% end %>

  <div class="mb-4 p-3 bg-light">
    <%= link_to 'Show all topics', topics_path, class: 'text-warning' %>
  </div>

  <div class="row">
    <div class="col-md-8 blog-main">
      <%= render @blogs %>

      <%= paginate @blogs %>
    </div><!-- /.blog-main -->

    <%= render 'sidebar' %>
  </div><!-- /.row -->
</main><!-- /.container -->

app/views/blogs/new.html.erb
<div class="container mt-5 mb-5">
  <div class="row">
    <main role="main" class="col-md-8">
      <h1>New Blog</h1>

      <hr>

      <%= render 'form', blog: @blog %>

      <% if policy(@blog).index? %>
        <div class="mt-3">
          <%= link_to 'Back', blogs_path %>
        </div>
      <% end %>
    </main>

    <%= render 'sidebar' %>
  </div>
</div>

app/views/blogs/show.html.erb
<div class="container mt-5 mb-5">
  <div class="row">
    <main role="main" class="col-md-8">
      <div>
        <h2 class="mb-4"><%= @blog.title %></h2>

        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><%= link_to 'Home', root_path %></li>
            <li class="breadcrumb-item"><%= link_to 'Blog', blogs_path %></li>
            <li class="breadcrumb-item"><%= link_to @blog.topic.title, topic_path(@blog.topic) %></li>
            <li class="breadcrumb-item active" aria-current="page"><%= @blog.title %></li>
          </ol>
        </nav>

        <%= render 'actions', blog: @blog %>

        <%= @blog.body %>
      </div>

      <% if policy(@comment).show? %>
        <hr>

        <%= render 'comments', blog: @blog, comment: @comment %>
      <% end %>
    </main>

    <%= render 'sidebar' %>
  </div>
</div>

app/views/blogs/show.js.erb
document.querySelector('[data-channel="comments"]').insertAdjacentHTML('beforeend', '<%= escape_javascript render @comments %>')
document.querySelector('[data-comments-pagination]').innerHTML = '<%= escape_javascript comments_pagination %>'