config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  resources :comments

  resources :portfolios, except: :show do
    put :sort, on: :collection
  end
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  resources :blogs do
    get :toggle_status, on: :member
  end

  get 'about-me' => 'pages#about'
  get 'contact' => 'pages#contact'

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', registration: 'account', sign_up: 'signup' }
  root 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies
  has_one_attached :main_image
  has_one_attached :thumb_image

  accepts_nested_attributes_for :technologies, allow_destroy: true, reject_if: ->(attrs) { attrs[:name].blank? }

  validates :title, :body, presence: true
  validates :main_image, :thumb_image, attached: true, content_type: ['image/png', 'image/jpg', 'image/jpeg'], size: { less_than: 2.megabytes }
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout 'portfolio'
  before_action :set_portfolio_item, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @portfolio_items = Portfolio.order(:position)
    authorize @portfolio_items
  end

  def show
    authorize @portfolio_item
  end

  def new
    @portfolio_item = Portfolio.new
    authorize @portfolio_item
  end

  def edit
    authorize @portfolio_item
  end

  def create
    @portfolio_item = Portfolio.new(portfolios_params)
    authorize @portfolio_item

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_url, notice: 'Your portfolio item is now live.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    authorize @portfolio_item

    respond_to do |format|
      if @portfolio_item.update(portfolios_params)
        format.html { redirect_to portfolios_url, notice: 'The record successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    authorize @portfolio_item
    @portfolio_item.destroy

    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Record was removed.' }
    end
  end

  def sort
    authorize :portfolio
    params[:order].each { |k, v| Portfolio.find_by_id(v[:id])&.update(position: v[:position]) }
    head :no_content
  end

  private
    def set_portfolio_item
      @portfolio_item = Portfolio.find(params[:id])
    end

    def portfolios_params
      params.require(:portfolio).permit(:title, :subtitle, :body, :main_image, :thumb_image, technologies_attributes: [:id, :name, :_destroy])
    end
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_with(model: portfolio_item, local: true) do |form| %>
  <% if portfolio_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(portfolio_item.errors.count, "error") %> prohibited this portfolio item from being saved:</h2>

      <ul>
        <% portfolio_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col">
      <h2 class="mb-4">Item</h2>

      <div class="field form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="field form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, class: 'form-control' %>
      </div>

      <div class="field form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: 'form-control', rows: 10 %>
      </div>

      <div class="field form-group">
        <%= form.label :main_image %>
        <%= form.file_field :main_image, class: 'form-control' %>
      </div>

      <div class="field form-group">
        <%= form.label :thumb_image %>
        <%= form.file_field :thumb_image, class: 'form-control' %>
      </div>
    </div>

    <div class="col">
      <h2 class="mb-4">Technologies</h2>

      <div>
        <%= form.fields_for :technologies do |technology_form| %>
          <%= render 'technology_fields', f: technology_form %>
        <% end %>

        <%= link_to_add_association '+', form, :technologies, class: 'btn btn-success' %>
      </div>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4" data-id="<%= portfolio_item.id if policy(portfolio_item).update? %>">
  <div class="card mb-4 shadow-sm">
    <%= image_tag(portfolio_item.thumb_image.variant(resize_to_limit: [350, 200]), alt: portfolio_item.title, class: 'img-fluid') if portfolio_item.thumb_image.attached? %>

    <div class="card-body">
      <h3 class="card-title"><%= portfolio_item.title %></h3>
      <h4><small><%= portfolio_item.subtitle %></small></h4>

      <div class="d-flex justify-content-between align-items-center mt-3">
        <% if policy(portfolio_item).show? || policy(portfolio_item).edit? || policy(portfolio_item).destroy? %>
          <div class="btn-group">
            <% if policy(portfolio_item).show? %>
              <%= link_to 'View', portfolio_show_path(portfolio_item), class: 'btn btn-sm btn-outline-secondary' %>
            <% end %>

            <% if policy(portfolio_item).edit? %>
              <%= link_to 'Edit', edit_portfolio_path(portfolio_item), class: 'btn btn-sm btn-outline-secondary' %>
            <% end %>

            <% if policy(portfolio_item).destroy? %>
              <%= link_to 'Delete', portfolio_item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-secondary' %>
            <% end %>
          </div>
        <% end %>

        <small class="text-muted"><%= time_ago_in_words portfolio_item.created_at %></small>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="field nested-fields form-group">
  <%= f.label :name %>
  <div class="input-group">
    <%= f.text_field :name, class: 'form-control' %>

    <div class="input-group-append">
      <%= link_to_remove_association '-', f, class: 'input-group-text btn bg-danger text-white font-weight-bold px-3' %>
    </div>
  </div>
</div>

app/views/portfolios/edit.html.erb
<main class="album py-5 bg-light">
  <div class="container">
    <h1>Edit this Portfolio Item</h1>

    <hr>

    <%= render 'form', portfolio_item: @portfolio_item %>
  </div>
</main>

app/views/portfolios/index.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">Etiam porta sem malesuada magna mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>

    <p>
      <%= link_to 'Find Out More about Me', about_me_path, class: 'btn btn-primary my-2' %>
      <%= link_to 'My Blog', blogs_path, class: 'btn btn-primary my-2' %>
    </p>
  </div>
</section>

<% if policy(@portfolio_items).new? %>
  <div class="pt-5 bg-light text-right">
    <div class="container">
      <%= link_to 'Create New Item', new_portfolio_path, class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row <%= 'sortable' if policy(@portfolio_items).update? %>">
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<main class="album py-5 bg-light">
  <div class="container">
    <h1>Create a new Portfolio Item</h1>

    <hr>

    <%= render 'form', portfolio_item: @portfolio_item %>
  </div>
</main>

app/views/portfolios/show.html.erb
<main class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <% if @portfolio_item.thumb_image.attached? %>
        <div class="col-md border">
          <%= image_tag @portfolio_item.main_image.variant(resize_to_limit: [600, 400]), alt: @portfolio_item.title, class: 'img-fluid' %>
        </div>
      <% end %>

      <div class="col-md">
        <div>
          <h1 class="mb-0"><%= @portfolio_item.title %></h1>
          <h2><small class="text-muted"><%= @portfolio_item.subtitle %></small></h2>

          <% if policy(@portfolio_item).edit? || policy(@portfolio_item).destroy? %>
            <div class="my-3">
              <div class="btn-group">
                <% if policy(@portfolio_item).edit? %>
                  <%= link_to 'Edit', edit_portfolio_path(@portfolio_item), class: 'btn btn-sm btn-outline-secondary' %>
                <% end %>

                <% if policy(@portfolio_item).destroy? %>
                  <%= link_to 'Delete', @portfolio_item, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-secondary' %>
                <% end %>
              </div>
            </div>
          <% end %>

          <p><%= @portfolio_item.body %></p>
        </div>

        <% unless @portfolio_item.technologies.empty? %>
          <hr>

          <div>
            <h2>Technologies Used</h2>

            <% @portfolio_item.technologies.each do |technology| %>
              <p><%= technology.name %></p>
            <% end %>
          </div>
        <% end %>

        <hr>

        <div>
          <%= link_to 'View all portfolio items', portfolios_path %>
        </div>
      </div>
    </div>
  </div>
</main>